/*
 * EXI_cfg.h
 *
 *  Created on: Aug 29, 2022
 *      Author: hp
 */

#ifndef MCAL_EXI_EXI_CFG_H_
#define MCAL_EXI_EXI_CFG_H_

/*MODES:
 * INT0_LOW_LEVEL-INT0_ANY_CHANGE-INT0_FALLING_EDGE-INT0_RISING_EDGE
 * INT1_LOW_LEVEL-INT1_ANY_CHANGE-INT1_FALLING_EDGE-INT1_RISING_EDGE
 * INT2_FALLING_EDGE-INT2_RISING_EDGE
 * */

#define INT0_PORT PORTD_ID
#define INT0_PIN PIN2_ID
#define INT0_MODE INT0_FALLING_EDGE

#define INT1_PORT PORTD_ID
#define INT1_PIN PIN3_ID
#define INT1_MODE INT1_ANY_CHANGE

#define INT2_PORT PORTB_ID
#define INT2_PIN PIN2_ID
#define INT2_MODE INT2_FALLING_EDGE

#endif /* MCAL_EXI_EXI_CFG_H_ */
