/*
 * TIMER1_cfg.h
 *
 *  Created on: Sep 13, 2022
 *      Author: mostafa_ebrahim
 */

#ifndef MCAL_TIMER1_TIMER1_CFG_H_
#define MCAL_TIMER1_TIMER1_CFG_H_

/*options of Timer1 Mode:
 * TIMER1_NORMAL_MODE
 * TIMER1_CTC_OCR1A
 * TIMER1_FAST_PWM_ICR1
 *
 * */
#define TIMER1_MODE TIMER1_FAST_PWM_ICR1

/*options of TIMER1 Clock Select:
*TIMER1_NO_CLK
*TIMER1_NO_PRESCALER
*TIMER1_8_PRESCALER
*TIMER1_64_PRESCALER
*TIMER1_256_PRESCALER
*TIMER1_1024_PRESCALER
*TIMER1_EXT_CLK_FALLING_EDGE
*TIMER1_EXT_CLK_RISINGING_EDGE
**/
#define TIMER1_CLOCK_SELECT TIMER1_8_PRESCALER

/*OC1 pin option CTC
 * TIMER1_OC1_DISCONNECTED
 * TIMER1_OC1_TOGGLE
 * TIMER1_OC1_CLR
 * TIMER1_OC1_SET
 *
 * */
#define TIMER1_OCP_PIN_MODE TIMER1_OC1_TOGGLE

/* interrupt state
 *
 * Options:
 * 1- TIMER1_INT_ENABLE
 * 2- TIMER1_INT_DISABLE
 * */
#define TIMER1_INTERRUPT_STATE_OVF TIMER1_INT_DISABLE
#define TIMER1_INTERRUPT_STATE_CTCA TIMER1_INT_ENABLE
#define TIMER1_INTERRUPT_STATE_CTCB TIMER1_INT_DISABLE
#define TIMER1_INTERRUPT_STATE_CE TIMER1_INT_ENABLE /*Capture Event*/

/*Input Capture State
 *
 * Options:
 * 1- TIMER1_ICU_ENABLE
 * 2- TIMER1_ICU_DISABLE
 * */
#define TIMER1_ICU_STATE TIMER1_ICU_DISABLE


/* TIMER1 FCPU frequency
 *
 *	Options:
 *	user specify the frequency
 * */
#define TIMER1_InputFreq 8000000UL


/*PWM Mode Options:
 * TIMER1_PWM_NON_INVERTING
 * TIMER1_PWM_INVERTING
 * NOTE:
 * NON_INVERTING:Duty Cycle->OCR
 * INVERTING:Duty Cycle ~OCR*/
#define TIMER1_PWM_MODE_OC1A TIMER1_PWM_NON_INVERTING
#define TIMER1_PWM_MODE_OC1B TIMER1_PWM_NON_INVERTING

/* OC1A Pin Configuration */
#define OC1A_PORT PORTD_ID
#define OC1A_PIN	 PIN5_ID

/* OC1B Pin Configuration */
#define OC1B_PORT PORTD_ID
#define OC1B_PIN	 PIN4_ID


#endif /* MCAL_TIMER1_TIMER1_CFG_H_ */
